"""empty message

Revision ID: 95dfd7fd6d87
Revises: 95878755079e
Create Date: 2022-01-22 21:19:36.636246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dfd7fd6d87'
down_revision = '95878755079e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
